version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: branchpro/docs/source/conf.py

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: ./docs/.requirements-docs.txt
   