name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python '3.10'
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: x64

      - name: install branchpro
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .
          python3 -m pip install coverage codecov
      - name: run coverage
        run: |
          coverage run run-tests.py --unit

      - name: codecov
        if: success()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          codecov
