# This runs documentation testing.

name: Check documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[docs]
    - name: Checks documentation
      run: |
        python run-tests.py --doctest
