# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: Run Unit Tests on Mac OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade setuptools==68.2.2  # Install or upgrade setuptools

      - name: Build for x86_64
        run: |
          arch -x86_64 /bin/bash -c "python3 setup.py build"
      - name: Test with unittest
        run: |
          python3 run-tests.py --unit