# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: Run Unit Tests on Mac OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set multibuild environment variables
      run: |
        echo "PLAT=x86_64" >> $GITHUB_ENV;
        echo "ARCHFLAGS=-arch x86_64" >> $GITHUB_ENV
        then echo "MB_PYTHON_OSX_VER=10.9" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .

    - name: Test with unittest
      run: |
        python3 run-tests.py --unit