# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Unit Tests on multiple python versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ${{ matrix.os-ver }}
    strategy:
      fail-fast: false
      matrix:
        py-ver: ['3.9', '3.10', '3.11', '3.12']
        os-ver: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.py-ver }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-ver }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install .
    - name: Test with unittest
      run: |
        python run-tests.py --unit
